# Generated by Django 4.1.7 on 2025-09-19 01:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("currencies", "0005_currencyconversionhistorial"),
    ]

    operations = [
        migrations.AddField(
            model_name="currencyconversionhistorial",
            name="source",
            field=models.CharField(default="paralelo", max_length=100, unique=True),
        ),
    ]
