# Generated by Django 4.1.7 on 2025-09-19 01:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("currencies", "0006_currencyconversionhistorial_source"),
    ]

    operations = [
        migrations.AlterField(
            model_name="currencyconversionhistorial",
            name="source",
            field=models.CharField(
                choices=[("paralelo", "Paralelo"), ("bcv", "BCV")],
                default="paralelo",
                max_length=100,
                unique=True,
            ),
        ),
    ]
