# Generated by Django 4.1.7 on 2025-09-22 14:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("currencies", "0006_currencyconversionhistorial_source"),
    ]

    operations = [
        migrations.AddField(
            model_name="currency",
            name="default_conversion_source",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
