# Generated by Django 4.1.7 on 2026-08-06 16:42

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("receivables", "0005_receivable_explicit_principal_usd"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("transactions", "0016_transactiongroup"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExpenseSharePartner",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "default_partner_percent",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0")),
                            django.core.validators.MaxValueValidator(Decimal("100")),
                        ],
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "contact",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="expense_share_partners",
                        to="receivables.contact",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ExpenseSharePeriod",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.PositiveSmallIntegerField()),
                (
                    "month",
                    models.PositiveSmallIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(12),
                        ]
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("draft", "draft"), ("finalized", "finalized")],
                        default="draft",
                        max_length=20,
                    ),
                ),
                (
                    "partner_percent",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0")),
                            django.core.validators.MaxValueValidator(Decimal("100")),
                        ],
                    ),
                ),
                (
                    "total_expenses_usd",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=14
                    ),
                ),
                (
                    "partner_share_usd",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=14
                    ),
                ),
                (
                    "my_share_usd",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=14
                    ),
                ),
                ("notes", models.CharField(blank=True, default="", max_length=500)),
                ("finalized_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "partner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="periods",
                        to="expense_shares.expensesharepartner",
                    ),
                ),
                (
                    "receivable",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="expense_share_period",
                        to="receivables.receivable",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ExpenseShareLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "expense_total_usd",
                    models.DecimalField(decimal_places=2, max_digits=14),
                ),
                (
                    "partner_share_usd",
                    models.DecimalField(decimal_places=2, max_digits=14),
                ),
                ("transaction_count", models.PositiveIntegerField(default=0)),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="expense_share_lines",
                        to="transactions.category",
                    ),
                ),
                (
                    "period",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lines",
                        to="expense_shares.expenseshareperiod",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ExpenseShareCategoryInclude",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="expense_share_includes",
                        to="transactions.category",
                    ),
                ),
                (
                    "partner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="includes",
                        to="expense_shares.expensesharepartner",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ExpenseShareCategoryExclude",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="expense_share_excludes",
                        to="transactions.category",
                    ),
                ),
                (
                    "partner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="excludes",
                        to="expense_shares.expensesharepartner",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="expenseshareperiod",
            constraint=models.UniqueConstraint(
                fields=("user", "partner", "year", "month"),
                name="unique_expense_share_period",
            ),
        ),
        migrations.AddConstraint(
            model_name="expensesharepartner",
            constraint=models.UniqueConstraint(
                fields=("user", "contact"),
                name="unique_expense_share_partner_per_user_contact",
            ),
        ),
        migrations.AddConstraint(
            model_name="expensesharecategoryinclude",
            constraint=models.UniqueConstraint(
                fields=("partner", "category"), name="unique_expense_share_include"
            ),
        ),
        migrations.AddConstraint(
            model_name="expensesharecategoryexclude",
            constraint=models.UniqueConstraint(
                fields=("partner", "category"), name="unique_expense_share_exclude"
            ),
        ),
    ]
