# Generated by Django 4.1.7

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("receivables", "0002_receivable_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="receivable",
            name="account",
        ),
        migrations.RemoveField(
            model_name="receivable",
            name="amount_given",
        ),
        migrations.RemoveField(
            model_name="receivable",
            name="amount_paid",
        ),
        migrations.RemoveField(
            model_name="receivable",
            name="amount_to_receive",
        ),
        migrations.RemoveField(
            model_name="receivable",
            name="status",
        ),
    ]
