# Generated by Django 4.1.7

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def migrate_contact_strings_to_fk(apps, schema_editor):
    Receivable = apps.get_model("receivables", "Receivable")
    Contact = apps.get_model("receivables", "Contact")

    for receivable in Receivable.objects.all().iterator():
        name = (receivable.contact_name or "").strip()
        if not name:
            name = "Unknown"
        contact, _ = Contact.objects.get_or_create(
            user_id=receivable.user_id,
            name=name,
        )
        receivable.contact = contact
        receivable.save(update_fields=["contact"])


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("receivables", "0003_rework_receivable"),
    ]

    operations = [
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=500)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="contact",
            constraint=models.UniqueConstraint(
                fields=("user", "name"), name="unique_contact_per_user"
            ),
        ),
        migrations.RenameField(
            model_name="receivable",
            old_name="contact",
            new_name="contact_name",
        ),
        migrations.AddField(
            model_name="receivable",
            name="contact",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="receivables",
                to="receivables.contact",
            ),
        ),
        migrations.RunPython(
            migrate_contact_strings_to_fk,
            migrations.RunPython.noop,
        ),
        migrations.RemoveField(
            model_name="receivable",
            name="contact_name",
        ),
        migrations.AlterField(
            model_name="receivable",
            name="contact",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="receivables",
                to="receivables.contact",
            ),
        ),
    ]
