# Generated by Django 4.1.7

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("receivables", "0004_contact_and_fk"),
    ]

    operations = [
        migrations.AddField(
            model_name="receivable",
            name="explicit_principal_usd",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=14, null=True
            ),
        ),
    ]
