# Generated by Django 4.1.7 on 2024-02-07 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.CharField(blank=True, default='', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='productlist',
            name='description',
            field=models.CharField(blank=True, default='', max_length=500, null=True),
        ),
    ]
