# Generated by Django 4.1.7 on 2025-03-14 20:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0004_product_user_productlist_user_productlistitem_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="productlist",
            name="period_end",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="productlist",
            name="period_start",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="productlist",
            name="period_type",
            field=models.CharField(
                choices=[("NO_PERIOD", "No Period"), ("MONTHLY", "Monthly")],
                default="NO_PERIOD",
                max_length=15,
            ),
        ),
        migrations.AddField(
            model_name="productlistitem",
            name="quantity_purchased",
            field=models.IntegerField(default=0),
        ),
    ]
