# Generated by Django 4.1.7 on 2023-09-22 23:41

from django.db import migrations, models

def convert_amount(apps, schema_editor):
    Transaction = apps.get_model('transactions', 'Transaction')
    for transaction in Transaction.objects.all():
        # 2 decimal places
        transaction.amount = int(transaction.amount * 100)
        transaction.save()

def revert_amount(apps, schema_editor):
    Transaction = apps.get_model('transactions', 'Transaction')
    for transaction in Transaction.objects.all():
        transaction.amount = float(transaction.amount / 100)
        transaction.save()

class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(convert_amount, revert_amount),
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=models.IntegerField(),
        ),
    ]
