# Generated by Django 4.1.7 on 2025-01-13 01:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("transactions", "0011_currencyexchange_comissions"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="to_main_currency_amount",
            field=models.IntegerField(null=True),
        ),
    ]
