# Generated by Django 4.1.7

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("receivables", "0003_rework_receivable"),
        ("transactions", "0014_transaction_bigint_amounts"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="receivable",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="transactions",
                to="receivables.receivable",
            ),
        ),
    ]
